### ISSUE TITLE
element.mozSrcObject = stream doesn't work in FF >= 34.0.5

### ISSUE THREAD

**Issue by juberti** [webrtcHacks/adapter#7] opened 2015-02-04 23:52 UTC
Migrated from https://github.com/webrtc/samples/issues/302

ibc commented on Dec 16, 2014
When Firefox is detected:

  // Attach a media stream to an element.
  attachMediaStream = function(element, stream) {
    console.log('Attaching media stream');
    element.mozSrcObject = stream;
  };
This no longer works in FF 34.0.5 (nor in the today's Nightly version). BTW the "old fashion?" element.src = URL.createObjectURL(stream) does work.

I know that this spec is changing and honestly I don't know how the standard will finally be.

Not sure how to "fix" adapter.js in order to apply one way or another depending on the version of FF.
Iñaki Baz Castillo

ibc commented on Dec 16, 2014
NOTE: The problem is that in FF 34.0.5 typeof element.mozSrcObject !== 'undefined' so...
Justin Uberti
 Owner
juberti commented on Dec 16, 2014
I think the currently preferred syntax in Moz is 'element.src = stream'. @samdutton
Iñaki Baz Castillo

ibc commented on Dec 17, 2014
Yep, and AFAIR that what the standard says (or will finally say). Anyhow, the problem is that a MediaStream object in Firefox stable 34.0.5 (and current Nightly) does include an attribute called mozSrcObject (but it does not work as before).
Iñaki Baz Castillo

ibc commented on Dec 17, 2014
@juberti No, Firefox 34 does not accept element.src = stream. Tested.

element.src = URL.createObjectURL(stream); seems the only way to make it work.

**Comment by juberti** [comment] 2015-02-05 20:11
@samdutton is there anything to do here?

**Comment by alvestrand** [comment] 2015-05-21 13:06
The way attachMediaStream() is written now, it should work for Firefox in any version (it checks for srcObject, mozSrcObject and src, in that order, does direct assignment on the 2 first ones, and goes via createObjectURL for the third).

Can someone confirm or deny this?

(I'd like to replace this function with a polyfilling setter, but that's a completely different question)

**Comment by jan-ivar** [comment] 2015-05-21 20:05
I think there's some confusion here. We use element.mozSrcObject in all our tests e.g. http://jsfiddle.net/etj2kaax so it should work. The closest I can think of to a problem is we had a period of [timing issues with calling .play() too soon after](https://bugzilla.mozilla.org/show_bug.cgi?id=879717) on non-autoplaying elements, and another with [onloadedmetadata](https://bugzilla.mozilla.org/show_bug.cgi?id=926753) but these are fixed now. Not sure if any of these were specific to using the mozSrcObject form.

Also, adapter.js still seems to use it https://github.com/webrtc/adapter/blob/master/adapter.js#L131

**Comment by jan-ivar** [comment] 2015-05-21 20:09
FWIW adapter.js works for me in FF38 using [peerconnection/constraints/index.html](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jan-ivar/samples/polyconstraints/src/content/peerconnection/constraints/index.html) from https://github.com/webrtc/samples/pull/493

**Comment by alvestrand** [comment] 2015-05-27 11:08
Based on comments: Doesn't seem to be a reproducible error. If it is ... someone needs to write a test.
Closing for now.

**Closed as completed by alvestrand** 2015-05-27 11:08 UTC
