### ISSUE TITLE
getUserMedia with advanced constraints is broken

### ISSUE THREAD

**Issue by ggarber** [webrtcHacks/adapter#408] opened 2017-01-09 10:35 UTC
**Browsers and versions affected**
Chrome 55 (at least, not tested with others)

**Description**

When calling getUserMedia with advanced constraints consisting in an object with multiple properties (f.e. width and height) adapter.js converts it to optional constraints and it fails because it requires multiple properties to come in separate constraints.

**Steps to reproduce**
Run from the command line: 
navigator.mediaDevices.getUserMedia({"audio":true,"video":{"advanced":[{"width":{"min":1280,"max":1280}, "height":{"min":720,"max":720}}]}}).then(console.log, console.log)

**Expected results**
MediaStream logged

**Actual results**
Error, invalid constraints

**Workaround**
Pass advanced constraints with multiple properties as separate constraints:
navigator.mediaDevices.getUserMedia({"audio":true,"video":{"advanced":[{"width":{"min":1280,"max":1280}}, {"height":{"min":720,"max":720}}]}}).then(console.log, console.log)

**Comment by fippo** [comment] 2017-01-12 08:59
paging @jan-ivar

**Comment by ggarber** [comment] 2017-01-12 08:59
@jan-ivar  Do you know why are we moving advanced constrains to optional constrains?  It breaks my app if I use adapter.js because of that.      Do we really need that change?

**Comment by jan-ivar** [comment] 2017-01-12 17:02
@ggarber The bug here is adapter shouldn't be messing with constraints at all in Chrome 55. That polyfill may have been useful long ago in older versions.

I see a couple of PRs (https://github.com/webrtc/adapter/pull/336 and https://github.com/webrtc/adapter/pull/371 before it) have tried to remove it, but seem to both have run into test errors and probably distractions.

And not rhetorical: What are you using advanced constraints for?

**Comment by ggarber** [comment] 2017-01-13 09:51
Should I make a small PR in the mean time just to leave the advanced constraints untouched?  

@jan-ivar We are using advanced constraints to set min/max&ideal resolution and framerate.   Shouldn't we be using them?  Any advice on the usage of them is more than welcomed.

**Comment by ngauthier** [comment] 2017-01-13 16:52
I'm in the same boat here. Have users reporting a framerate of 3 when we are setting ideal to 12 (I have confirmed it). I believe it's this issue. Happy to help debug if necessary.

Nick

**Comment by jan-ivar** [comment] 2017-01-14 18:00
@ggarber Use [new constraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Parameters):
```js
video: {
  width: {min: 1024, ideal: 1280, max: 1920},
  height: {min: 776, ideal: 720, max: 1080}
}
```
@ngauthier Does it work without adapter?

**Comment by ngauthier** [comment] 2017-01-14 18:46
@jan-ivar I haven't tried it without. I'll give it a shot when I'm back to work Tuesday. Thanks!

**Comment by voltrevo** [comment] 2017-01-15 23:37
@jan-ivar We found Chrome does not support `ideal`, so we try first to get an exact value by setting {min, max} to the same thing (I guess Chrome didn't support `exact` either, this may have changed or maybe we just went along with min, max because they worked), then we ask for `ideal` in the next constraint set so that at least Firefox can try to get the best match, and Chrome ignores it but will fallback to whatever its default is.

**Comment by jan-ivar** [comment] 2017-01-17 17:21
@voltrevo [Works fine for me](https://jsfiddle.net/jib1/9t3szw0L/) in Chrome 55. Can we see your source?

**Comment by voltrevo** [comment] 2017-01-17 23:17
@jan-ivar yeah I found yesterday that exact works now in chrome too. The important one that's missing is ideal.

**Comment by voltrevo** [comment] 2017-01-17 23:18
@jan-ivar I'm on a bus atm but can make a snippet for you soon if you like.

**Comment by jan-ivar** [comment] 2017-01-18 03:01
@voltrevo Just remove the `width` constraint and you'll see ideal constraints work too (plain values are ideal by default).

**Comment by voltrevo** [comment] 2017-01-19 04:18
@jan-ivar Chrome doesn't seem to treat them the same, e.g. https://jsfiddle.net/7yevnvu3/ - you get 640x480. But if you specify `width: {exact: 1280}` you get 1280x720.

**Comment by jan-ivar** [comment] 2017-01-19 14:38
@voltrevo I can reproduce it. I think you've found a Chrome bug! Please [file a bug on Chrome](http://crbug.com/). With adapter.js it wfm (1280x720), without it doesn't (640x480). Cc @alvestrand.

**Comment by alvestrand** [comment] 2017-01-19 14:40
We're working on ideal, aiming for M58. At the moment we accept and ignore it.

**Comment by jan-ivar** [comment] 2017-01-19 16:10
Ok so maybe we shouldn't remove the constraints polyfill just yet then. @fippo FYI ^

I'll provide a PR here then.

**Comment by voltrevo** [comment] 2017-01-19 23:57
@jan-ivar Yeah I probably should've done that earlier :-P, [new Chrome bug here](https://bugs.chromium.org/p/chromium/issues/detail?id=682887&can=2&q=getusermedia%20constraints&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). CC @alvestrand

**Comment by alvestrand** [comment] 2017-01-20 09:13
Chrome bug assigned and made dependent on "implementing the fix" bug.

Should we close this? I don't see an adapter action that can be taken.

**Comment by jan-ivar** [comment] 2017-01-20 16:51
@alvestrand The [OP](https://github.com/webrtc/adapter/issues/408#issue-199520413) is a bug in the constraints polyfill: It doesn't support multiple constraints per entry in the advanced array. I can fix that, or we can yell at people using advanced. I'm happy to do the latter.

**Comment by kekkokk** [comment] 2017-04-19 07:18
I saw that Chrome consider the advanced array option in "reverse" order, starting from the last.
Firefox, instead, works as per [W3C Specification](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediatrackconstraints-advanced):

> The ordering of advanced ConstraintSets is significant. In the preceding example it is impossible to satisfy both the 1920x1280 ConstraintSet and the 4x3 aspect ratio ConstraintSet ....

Is that a chrome bug? are you considering this difference?

**Comment by henbos** [comment] 2017-04-19 09:18
Can you comment, @guidou?

**Comment by guidou** [comment] 2017-04-19 09:27
Chrome 59 has support for spec-compliant video constraints. 
For audio, standard syntax is accepted, but ideal is ignored and processing is not according to spec. We are aiming at adding spec-compliant audio constraints processing  in 60.

**Comment by fippo** [comment] 2017-06-14 09:22
@ggarber is it ok if we close this as a dupe of #553? Send complaints my way if not :-)

**Comment by Hoopstr42** [comment] 2017-08-21 17:05
I'm having issues with passing any constraints at all in chrome v 59.0.3071.125 on my S8. If any constraints are passed the browser crashes. 
Works well on every other device and chrome version I have tried even v 59.0.3071.115 on a S6.

I can post my actual code if needed but the [jsfiddle](https://jsfiddle.net/jib1/9t3szw0L/) posted above by @jan-ivar crashes it as well.  

Is this an open issue? or is there a work around? I have a project that goes live next week that I am relying on this to work.

**Comment by guidou** [comment] 2017-10-01 19:09
@Hoopstr42 is the problem you had still an issue? If so, please file a chromium bug at http://crbug.com

**Closed as completed** 2017-12-27 12:04 UTC
Labels: bug-in-chrome
