### ISSUE TITLE
Firefox 59 now uses transceivers

### ISSUE THREAD

**Issue by kekkokk** [webrtcHacks/adapter#760] opened 2018-01-31 08:38 UTC
**Browsers and versions affected**
Firefox >= 59

**Description**
When I try to createoffer with {offerToReceiveAudio: false, offerToReceiveVideo: false} a peerconnection with both medias in direction sendrecv are created

**Steps to reproduce**
https://jsfiddle.net/q8ww8wbc/4/

**Expected results**
senodnly direction

**Actual results**
sendrecv direction

**Comment by fippo** [comment] 2018-01-31 09:31
your reproduction does not even use adapter.js so its pretty clear that this is a browser issue.

@jan-ivar might know more, including bugzilla links, i thought this was fixed? Possibly https://bugzilla.mozilla.org/show_bug.cgi?id=1425618

**Comment by kekkokk** [comment] 2018-01-31 09:47
because nils replied to me that is because of new transceiver implementation and set the WORKSFORME tag.

https://bugzilla.mozilla.org/show_bug.cgi?id=1433953

I dind't noticed there was already an issue opened marked as fixed so meanwhile I opened a pr, but if they said that already fixed this and will land in 59 my pr is probably not useful

https://github.com/webrtc/adapter/pull/762

**Comment by fippo** [comment] 2018-01-31 09:55
the fiddle still reproduces in 59 so something is wrong. also tagging @nils-ohlmeier

**Comment by jan-ivar** [comment] 2018-01-31 17:36
Looks like we messed it up. I've re-opened the bug.

**Comment by KaptenJansson** [comment] 2018-02-01 08:37
Closing as it's an issue in Firefox.

**Comment by KaptenJansson** [comment] 2018-02-01 08:37
And thanks for filing btw!

**Closed as completed by KaptenJansson** 2018-02-01 08:37 UTC
Labels: bug-in-firefox
