### ISSUE TITLE
Safari 11 support?

### ISSUE THREAD

**Issue by anildigital** [webrtcHacks/adapter#685] opened 2017-09-26 17:26 UTC
**Browsers and versions affected**
Safari 11

**Description**
How far will it take to make it work with Safari 11? Are there any major blockers?

**Steps to reproduce**
Multiple errors

**Expected results**
Working fine with Safari 11

**Actual results**
Right now there are errors with Safari 11

**Comment by youennf** [comment] 2017-09-26 17:29
Can you elaborate on the errors you are seeing?

**Comment by KaptenJansson** [comment] 2017-10-10 15:10
Ping

**Comment by davies147** [comment] 2017-10-10 16:21
I am not the OP, but I can confirm that the vast majority of errors seem to
be with Safari 11's implementation, and that I have raised bug reports with
Apple.

Each of the reports I have raised have been "confirmed" as "duplicates",
which means they vanish from my queue - I am hopeful that it means they
will be fixed though.

Most of the issues I had are around media selection, and failing to run
several of the readily available WebRTC test cases that exist online.

If I manage to find any adapter specific issues, I'll be raising them here
for sure :)

Hope that helps,
Steve

**Comment by gururise** [comment] 2017-10-16 16:51
I too can confirm Safari 11 on iOS 11 (currently testing on 11.0.3) is extremely unstable.  Couple of known issues:
* iOS < - > Android (Chrome) is not working (possibly an h264 bug on Android side)
* iOS -> Desktop (Chrome/Firefox) is very unstable.  If, for example, you take a screenshot during a video call, you can almost always crash iOS.
* iOS < - > iOS is even worse!

Also, most of the examples for adapter.js seem to be not working on my iOS 11.0.3 device.

**Comment by youennf** [comment] 2017-10-16 17:15
@gururise, would you be able to file bugs on bugs.webkit.org?

**Comment by ee11131** [comment] 2017-11-03 12:58
In my case, I am using the latest SimpleWebRTC with adapter.js. I was able to establish a working video call in Chrome to Chrome and Safari to Safari. However, it is not working in Chrome to Safari and vice-versa. No errors are shown, the connection just isn't established. Can this be because the safariShim.shimPeerConnection isn't implemented or should it work anyway?

**Comment by ptman** [comment] 2017-11-03 13:35
I have success with Safari and various combinations on https://azureubuntu2.lyc.fi/ . It's using the latest adapter, as you can see.

**Comment by CezaryDanielNowak** [comment] 2017-11-16 19:04
For me getUserMedia + adapterjs works fine on iOS11. The only thing I needed to add to `video` tag was:
```
  autoplay: 'autoplay',
  playsinline: 'playsinline',
```

**Comment by KaptenJansson** [comment] 2018-01-31 09:55
Closing this for now, Safari support will most likely be added once it's more stable and supporting API's are in place.

**Closed as completed by KaptenJansson** 2018-01-31 09:55 UTC

**Comment by sebhaase** [comment] 2018-01-31 16:46
My feeling would be to rather leave this issue open until then ....
Is there any  reference to when to expect support from osX  and iOS ?

Thanks,
Sebastian

**Comment by ptman** [comment] 2018-01-31 17:25
Am I missing something? Safari seems to work for me. Or is it only basic, and not the whole API?
