### ISSUE TITLE
Chrome 59 supports spec-constraints

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#553] opened 2017-05-17 09:24 UTC
Chrome 59 supports spec-constraints for getUserMedia so we should stop translating constraints.

@guidou: the release notes are quite unhelpful about saying where this was actually fixed, can you point to a bug? This might be https://bugs.chromium.org/p/chromium/issues/detail?id=682887 but that has no associated CLs so it is hard to judge what works and what is still left for https://bugs.chromium.org/p/chromium/issues/detail?id=657733

**Comment by guidou** [comment] 2017-05-17 11:02
Chrome 59 supports spec-compliant video constraints for getUserMedia, but not audio constraints.
The audio work is still going on, aiming to finish in 60.
http://crbug.com/657733 tracks both, so it will be closed when the audio work lands (maybe we should have used separate bugs, but we didn't know at the time).
http://crbug.com/682887 was basically tracking ideal support for video constraints and is closed as Fixed.

**Comment by malakagit** [comment] 2017-07-17 15:49
I'm experiencing this as well when using getUserMedia but inconsistently between different PC's.

We are using Xsplit to screencast, and as described on the bug we are seeing 640x480 in webrtc-internals and the quality is degraded.  

is there anything I can do to force the resolution for chrome users?  I've tried setting min and ideal constraints but no luck.

**Comment by bbaldino** [comment] 2017-09-29 21:55
@fippo any update on this?  we're trying to move jitsi over to using adapter, but hitting issues when trying to specify video constraints.  i've got a fiddle here: https://jsfiddle.net/sa6pjux1/ (NOTE: you'll need to make sure the 'load type' in the javascript config menu is set to `No Wrap - in <body>` for it to properly load the adpaterjs file there)

if you use a camera which doesn't support 1080p (built-in facetime camera for example), it'll fall back to 640x480.  If you comment out including adapter, it'll get 1280x720 (which is what we want).

**Comment by fippo** [comment] 2017-09-30 06:34
that sounds like a bug... @jan-ivar any idea?

**Comment by guidou** [comment] 2017-10-01 19:13
@bbaldino 
I tried https://jsfiddle.net/sa6pjux1/ in Chrome 62 and Firefox 55 with a webcam that has maximum 1280x720 and it works as expected with and without adapter.js. I get 1280x720 in all cases.
If you think there's an issue in Chrome, file a bug at http://crbug.com

**Comment by jan-ivar** [comment] 2017-10-02 13:48
@bbaldino Note if you "Update" and "Set as base" your fiddle after you've fixed the load type to `No Wrap - in <body>`, then it should be saved, and we won't have to remember to flip it (less confusion).

I can reproduce in Chrome 61 (get `640x480` when it should've been `1280x720`) only with adapter. Works fine without.

This is because the adapter.js constraints polyfill is inferior to Chrome's implementation. Removing it is overdue. 

@guidou Do we want the cutoff to be 59, 60 or 61? Do we still need to polyfill the audio constraints?

**Comment by bbaldino** [comment] 2017-10-02 16:36
thanks @jan-ivar , i should have specified before that i was seeing this in chrome 61.

**Comment by bbaldino** [comment] 2017-10-02 18:37
also @jan-ivar is there anything planned to handle the screenshare side of things?  i noticed chrome still wants the old-style constraints and chromeMediaSource/chromeMediaSourceId for screenshare.

**Comment by fippo** [comment] 2017-10-02 18:56
unfortunately the webrtc product management remained silent to inquiries about the need for an extension... which is the main reason this is currently not shim-able in a good way.

**Comment by jan-ivar** [comment] 2017-10-03 02:14
@bbaldino The plan for adapter would need to be to implement the [spec](https://w3c.github.io/mediacapture-screen-share/#navigatorusermedia-additions), which is `getDisplayMedia`.

Presumably, `width`, `height`, and `frameRate` constraints would let users downscale output.

**Comment by jan-ivar** [comment] 2017-10-06 17:33
Based on https://github.com/webrtc/adapter/issues/553#issuecomment-333539631 I think the action item here is to remove the constraints polyfill in Chrome 61.

**Comment by fippo** [comment] 2017-10-06 18:24
I made a PR to remove the polyfill in Chrome61+. I think this needs to be a major version bump since the change in behaviour that is not covered by tests is unknown.

**Closed as completed** 2017-10-11 14:06 UTC
